name: docker-build-publish
on:
  # schedule:
  #   - cron: '30 22 * * *'
  push:
    branches: none # [ main ]
    # Publish semver tags as releases.
    tags: none # [ 'v*.*.*' ]
  pull_request:
    branches: none # [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build-docker:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: 'suricato.com.br'
    steps:
      - uses: actions/checkout@v3
      - name: Configurando NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm install

  push-docker:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: 'suricato.com.br'
    needs: build-docker
    steps:
      - uses: actions/checkout@v3
      - name: Subindo para o dockerhub
        run: echo Empurrando pra dockerhub
      
