name: docker-build-exemple

on:
  push:
    branches: none # [ main ]
  pull_request:
    branches: none # [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build-container:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      working-directory: suricato-control-bot

      run: docker build . --file Dockerfile --tag suricato-control-bot:$(date +%s)
